Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: sato-sa.to
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sato-sa.to
Outputs:
  SatoSatoBucket:
    Value: !Ref Bucket
  SatoSatoHoztedZone:
    Value: !Ref HostedZone
